- hosts: all
  become: yes
  tasks:
   - name: Install required packages for docker-ce
     yum:
       name: [yum-utils, device-mapper-persistent-data, lvm2]
       state: present
       update_cache: true

   - name: add docker-ce repository
     command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

   - name: install docker-ce, docker-ce-cli containerd.io
     yum:
       name: [docker-ce, docker-ce-cli, containerd.io]
       state: present
       update_cache: true

   - name: start Docker
     service:
       name: docker
       state: started

   - name: disable SELinux
     command: setenforce 0

   - name: disable SELinux on reboot
     selinux:
       state: disabled

   - name: Remove swapfile from /etc/fstab
     mount:
       name: swap
       fstype: swap
       state: absent

   - name: Disable swap
     command: swapoff -a
     when: ansible_swaptotal_mb > 0

   - name: Disable and stop firewalld
     service:
       name: firewalld
       state: stopped
       enabled: no

   - name: Create /etc/docker directory
     file:
       path: /etc/docker
       state: directory

   - name: Create docker daemon json with systemd cgroup-driver
     copy:
      dest: "/etc/docker/daemon.json"
      content: |
        {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
        "max-size": "100m"
          },
          "storage-driver": "overlay2",
          "storage-opts": [
        "overlay2.override_kernel_check=true"
          ]
        }

   - name: Create docker systemd service directory
     file:
       path: /etc/systemd/system/docker.service.d
       state: directory

   - name: Reload docker service
     service:
       name: docker
       state: reloaded

   - name: Restart docker service
     service:
       name: docker
       state: restarted

   - name: ensure net.bridge.bridge-nf-call-ip6tables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-ip6tables
      value: 1
      state: present

   - name: ensure net.bridge.bridge-nf-call-iptables is set to 1
     sysctl:
      name: net.bridge.bridge-nf-call-iptables
      value: 1
      state: present

   - name: add Kubernetes' YUM repository
     yum_repository:
      name: Kubernetes
      description: Kubernetes YUM repository
      baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      gpgcheck: yes

   - name: install kubelet
     yum:
        name: kubelet-1.13.3
        state: present
        update_cache: true

   - name: install kubeadm
     yum:
        name: kubeadm-1.13.3
        state: present

   - name: start kubelet
     service:
       name: kubelet
       enabled: yes
       state: started

- hosts: master
  become: yes
  tasks:
   - name: install kubectl
     yum:
        name: kubectl-1.13.3
        state: present
        allow_downgrade: yes

